const actionType = {
    GET_COURSE_LIST: "GET_COURSE_LIST",
    GET_COURSE_LIST_SUCCESS: "GET_COURSE_LIST_SUCCESS",
    GET_COURSE_LIST_FAILURE: "GET_COURSE_LIST_FAILURE",
    GET_COURSE_DETAIL: "GET_COURSE_DETAIL",
    GET_COURSE_DETAIL_SUCCESS: "GET_COURSE_DETAIL_SUCCESS",
    GET_COURSES_DETAIL_FAILURE: "GET_COURSES_DETAIL_FAILURE",
    POST_NEW_COURSE: "POST_NEW_COURSE",
    POST_NEW_COURSE_SUCCESS: "POST_NEW_COURSE_SUCCESS",
    POST_NEW_COURSE_FAILURE: "POST_NEW_COURSE_FAILURE",
    CREATE_NEW_COURSE: "CREATE_NEW_COURSE",
    DELETE_COURSE: "DELETE_COURSE",
    DELETE_COURSE_SUCCESS: "DELETE_COURSE_SUCCESS",
    DELETE_COURSE_FAILURE: "DELETE_COURSE_FAILURE",
    UPDATE_COURSE: "UPDATE_COURSE",
    UPDATE_CURRENT_COURSE: "UPDATE_CURRENT_COURSE",
    UPDATE_COURSE_SUCCESS: "UPDATE_COURSE_SUCCESS",
    UPDATE_COURSE_FAILURE: "UPDATE_COURSE_FAILURE",
};

export default actionType;