const actionType = {
    REGISTER_NEW_USER: 'REGISTER_NEW_USER',
    ADD_NEW_USER: 'ADD_NEW_USER',
    ADD_NEW_USER_SUCCESS: 'ADD_NEW_USER_SUCCESS',
    ADD_NEW_USER_FAILURE: 'ADD_NEW_USER_FAILURE',
    LOGIN: 'LOGIN',
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    LOGOUT: 'LOGOUT',
    GET_USER_DETAILS: 'GET_USER_DETAILS',
    GET_USER_DETAILS_SUCCESS: 'GET_USER_DETAILS_SUCCESS',
    GET_USER_DETAILS_FAILURE: 'GET_USER_DETAILS_FAILURE',
}

export default actionType;