const actionType = {
    GET_AUTHOR_LIST: 'GET_AUTHOR_LIST',
    GET_AUTHOR_LIST_SUCCESS: 'GET_AUTHORS_SUCCESS',
    GET_AUTHOR_LIST_FAILURE: 'GET_AUTHORS_FAILURE',
    CREATE_NEW_AUTHOR: 'CREATE_NEW_AUTHOR',
    CREATE_NEW_AUTHOR_SUCCESS: 'CREATE_NEW_AUTHOR_SUCCESS',
    CREATE_NEW_AUTHOR_FAILURE: 'CREATE_NEW_AUTHOR_FAILURE',
    DELETE_AUTHOR: 'DELETE_AUTHOR',
    DELETE_AUTHOR_SUCCESS: 'DELETE_AUTHOR_SUCCESS',
    DELETE_AUTHOR_FAILURE: 'DELETE_AUTHOR_FAILURE',
}

export default actionType;